server:
  port: 8080
spring:
  #数据库连接配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&&serverTimezone=GMT
    username: root
    password: 123456
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    cache: false

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hntyy.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

#日志配置
logging:
  config: classpath:log4j2-spring.xml
  level:
    cn.jay.repository: trace